apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports: 
        - containerPort: 3306
      # Importar todas as variáveis de ambiente de uma vez
      envFrom: 
        - configMapRef:
            name: db-noticias-configmap
      
     # env: # varaveis de ambiente - o ideal é usar config map
     #   - name: "MYSQL_ROOT_PASSWORD"
     #     value: "q1w2e3r4"
     #   - name: "MYSQL_DATABASE"
     #     value: "empresa"
     #   - name: "MYSQL_PASSWORD"
     #     value: "q1w2e3r4"

     # env: - importação individual das chaves
     #   - name: MYSQL_ROOT_PASSWORD
     #     valueFrom:
     #       configMapKeyRef:
     #         name: db-noticias-configmap
     #         key: MYSQL_ROOT_PASSWORD