apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    # label para identificar como o service vai encontrar esse pod
    app: segundo-pod # chave = app, valor = segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80