apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort # vai expor para máquinas fora do cluster
  ports:
    - port: 80
    #targetPort: 80 definido automaticamente
      nodePort: 30000 # 30000-32767
  selector:
    app: primeiro-pod